/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Chatbot } from "./Chatbot";
import { ChatbotCountArgs } from "./ChatbotCountArgs";
import { ChatbotFindManyArgs } from "./ChatbotFindManyArgs";
import { ChatbotFindUniqueArgs } from "./ChatbotFindUniqueArgs";
import { DeleteChatbotArgs } from "./DeleteChatbotArgs";
import { ChatbotService } from "../chatbot.service";
@graphql.Resolver(() => Chatbot)
export class ChatbotResolverBase {
  constructor(protected readonly service: ChatbotService) {}

  async _chatbotsMeta(
    @graphql.Args() args: ChatbotCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Chatbot])
  async chatbots(
    @graphql.Args() args: ChatbotFindManyArgs
  ): Promise<Chatbot[]> {
    return this.service.chatbots(args);
  }

  @graphql.Query(() => Chatbot, { nullable: true })
  async chatbot(
    @graphql.Args() args: ChatbotFindUniqueArgs
  ): Promise<Chatbot | null> {
    const result = await this.service.chatbot(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Chatbot)
  async deleteChatbot(
    @graphql.Args() args: DeleteChatbotArgs
  ): Promise<Chatbot | null> {
    try {
      return await this.service.deleteChatbot(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
