/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ChatbotService } from "../chatbot.service";
import { ChatbotCreateInput } from "./ChatbotCreateInput";
import { Chatbot } from "./Chatbot";
import { ChatbotFindManyArgs } from "./ChatbotFindManyArgs";
import { ChatbotWhereUniqueInput } from "./ChatbotWhereUniqueInput";
import { ChatbotUpdateInput } from "./ChatbotUpdateInput";

export class ChatbotControllerBase {
  constructor(protected readonly service: ChatbotService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Chatbot })
  async createChatbot(
    @common.Body() data: ChatbotCreateInput
  ): Promise<Chatbot> {
    return await this.service.createChatbot({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Chatbot] })
  @ApiNestedQuery(ChatbotFindManyArgs)
  async chatbots(@common.Req() request: Request): Promise<Chatbot[]> {
    const args = plainToClass(ChatbotFindManyArgs, request.query);
    return this.service.chatbots({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Chatbot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async chatbot(
    @common.Param() params: ChatbotWhereUniqueInput
  ): Promise<Chatbot | null> {
    const result = await this.service.chatbot({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Chatbot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateChatbot(
    @common.Param() params: ChatbotWhereUniqueInput,
    @common.Body() data: ChatbotUpdateInput
  ): Promise<Chatbot | null> {
    try {
      return await this.service.updateChatbot({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Chatbot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteChatbot(
    @common.Param() params: ChatbotWhereUniqueInput
  ): Promise<Chatbot | null> {
    try {
      return await this.service.deleteChatbot({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
